const { words } = require('./words.js');

// This file has a set of tools to help with cleaning and updating word lists


function compareWords(category) {
  if (!words[category]) {
    console.log(`Category "${category}" not found in the words object.`);
    return;
  }

  const possibleWordAddition = candidateWords[category];
  const uniquePossibleWordAddition = [...new Set(possibleWordAddition)];

  const categoryWords = words[category];
  const newWords = uniquePossibleWordAddition.filter(word => !categoryWords.includes(word));
  const newWordsCount = newWords.length;
  const existingWordsCount = uniquePossibleWordAddition.filter(word => categoryWords.includes(word)).length;

  console.log(`Category: ${category}`);
  console.log(`Count of words already in the category: ${existingWordsCount}`);
  console.log(`Count of new words that can be added: ${newWordsCount}`);
  console.log("New words that can be added:");
  console.log(JSON.stringify(newWords));
}

// Example ChatGPT query: generate a list of 200 animate nouns. make them all lowercase. format as a js array.  all on one line no line breaks.


// Step 1 - need to update the word lists above from the real copy in util.js before running
// Step 2 - update the category (last line of this file)
// Step 3 - run with `node wordListUtils.js`

// There are plenty of extra words in the canddiate word lists here, so they should be useful into the future if other additional words are needed.
const candidateWords = {
  "noun-animate": ["crocodile","salamander","sea lion","jellyfish","lobster","butterfly","dragonfly","grasshopper","scorpion","centipede","millipede","grandmother","grandfather","chef","astronaut","electrician","programmer","politician","princess","elf","ogre","unicorn","phoenix","griffin","werewolf","vampire","ghost","angel","god","goddess","robot","cyborg","chimpanzee","orangutan","kangaroo","platypus","echidna","rhinoceros","hippopotamus","polar bear","grizzly bear","raccoon","hedgehog","manatee","porpoise","narwhal","orca","beluga","albatross","kiwi","kestrel","woodpecker","ibis","chameleon","komodo dragon","boa constrictor","cobra","axolotl","swordfish","piranha","barracuda","starfish","sea urchin","anemone","coral"],
  "noun-concrete": ["table", "chair", "book", "pen", "lamp", "phone", "computer", "shoe", "hat", "shirt", "pants", "cup", "plate", "fork", "spoon", "knife", "bowl", "bottle", "glass", "window", "door", "wall", "floor", "ceiling", "roof", "bed", "pillow", "blanket", "sofa", "television", "remote", "clock", "watch", "calendar", "picture", "painting", "sculpture", "vase", "plant", "flower", "tree", "grass", "rock", "stone", "mountain", "river", "ocean", "beach", "sand", "cloud", "rain", "snow", "ice", "sun", "moon", "star", "planet", "galaxy", "universe", "atom", "molecule", "cell", "tissue", "organ", "bone", "muscle", "skin", "hair", "nail", "tooth", "eye", "ear", "nose", "mouth", "tongue", "finger", "thumb", "hand", "arm", "leg", "foot", "toe", "knee", "elbow", "shoulder", "hip", "neck", "head", "brain", "heart", "lung", "liver", "kidney", "stomach", "intestine", "blood", "vein", "artery", "nerve", "tendon", "car", "truck", "bus", "train", "plane", "boat", "ship", "bicycle", "motorcycle", "scooter", "skateboard", "roller skate", "wheel", "tire", "engine", "battery", "wire", "cable", "plug", "socket", "bulb", "switch", "button", "keyboard", "mouse", "screen", "speaker", "microphone", "camera", "telescope", "microscope", "mirror", "lens", "prism", "magnet", "compass", "thermometer", "barometer", "scale", "ruler", "pencil", "eraser", "paper", "notebook", "magazine", "newspaper", "envelope", "stamp", "coin", "bill", "wallet", "purse", "backpack", "suitcase", "box", "bag", "basket", "bucket", "can", "bottle", "jar", "container", "lid", "cap", "cork", "key", "lock", "chain", "rope", "string", "thread", "needle", "pin", "nail", "screw", "bolt", "nut", "washer", "spring", "gear", "lever", "pulley", "wedge", "inclined plane", "wheel and axle", "hammer", "screwdriver", "wrench", "pliers", "saw", "drill", "chisel", "file", "sandpaper", "brush", "sponge", "soap", "towel", "toothbrush", "comb"],
  "verb": ["run", "walk", "jump", "skip", "hop", "leap", "dance", "swim", "dive", "float", "sink", "fly", "soar", "glide", "climb", "crawl", "slide", "slither", "roll", "tumble", "fall", "rise", "lift", "drop", "throw", "catch", "toss", "pitch", "hit", "strike", "kick", "punch", "slap", "pat", "tap", "knock", "push", "pull", "drag", "lift", "carry", "hold", "grasp", "clutch", "squeeze", "pinch", "twist", "turn", "spin", "rotate", "revolve", "swing", "sway", "shake", "tremble", "shiver", "quake", "vibrate", "oscillate", "pulsate", "beat", "throb", "pound", "hammer", "drill", "bore", "pierce", "puncture", "stab", "poke", "prod", "jab", "cut", "slice", "chop", "dice", "mince", "grate", "shred", "tear", "rip", "split", "crack", "break", "shatter", "crush", "smash", "demolish", "destroy", "wreck", "build", "construct", "assemble", "create", "make", "form", "shape", "mold", "sculpt", "carve", "paint", "draw", "sketch", "doodle", "write", "type", "print", "copy", "scan", "fax","send", "receive", "transmit", "broadcast", "stream", "upload", "download", "install", "uninstall", "update","upgrade", "downgrade", "reboot", "restart", "shut down", "turn on", "turn off", "switch", "toggle", "flip","open", "close", "shut", "lock", "unlock", "bolt", "unbolt", "fasten", "unfasten", "tie","untie", "knot", "unknot", "wrap", "unwrap", "pack", "unpack", "fold", "unfold", "bend","straighten", "flatten", "crumple", "smooth", "iron", "press", "polish", "shine", "clean", "wash","rinse", "dry", "wipe", "sweep", "vacuum", "mop", "scrub", "scour", "sanitize", "disinfect", "sterilize", "cook", "bake", "fry", "grill", "roast", "boil", "simmer", "steam", "stew","brew", "ferment", "distill", "mix", "blend", "stir", "whisk", "beat", "knead", "roll", "spread", "sprinkle", "pour", "drip", "splash", "spill", "leak", "seep", "ooze", "flow"],
  "adj": ["big", "small", "tall", "short", "wide", "narrow", "long", "brief", "high", "low", "deep", "shallow", "thick", "thin", "fat", "skinny", "heavy", "light", "fast", "slow", "quick", "sluggish", "strong", "weak", "hard", "soft", "rough", "smooth", "sharp", "dull", "hot", "cold", "warm", "cool", "bright", "dim", "shiny", "dull", "clear", "opaque", "transparent", "cloudy", "clean", "dirty", "neat", "messy", "tidy", "cluttered", "organized", "chaotic", "simple", "complex", "easy", "difficult", "straightforward", "complicated", "plain", "fancy", "ornate", "minimalist", "beautiful", "ugly", "pretty", "handsome", "gorgeous", "hideous", "attractive", "repulsive", "charming", "revolting", "delightful", "awful", "pleasant", "unpleasant", "agreeable", "disagreeable", "friendly", "hostile", "kind", "cruel", "gentle", "harsh", "tender", "rough", "mild", "severe", "calm", "agitated", "peaceful", "violent", "quiet", "loud", "silent", "noisy", "melodious", "discordant", "harmonious", "jarring", "sweet", "sour", "bitter", "salty", "spicy", "bland", "tasty", "flavorful", "delicious", "disgusting", "appetizing", "unappetizing", "fragrant", "stinky", "aromatic", "foul", "fresh", "stale", "new", "old", "modern", "ancient", "contemporary", "outdated", "young", "elderly", "youthful", "mature", "childish", "adult", "infantile", "grown-up", "alive", "dead", "lively", "lifeless", "energetic", "lethargic", "vigorous", "feeble", "active", "passive", "dynamic", "static", "fluid", "rigid", "flexible", "stiff", "elastic", "inelastic", "soft", "hard", "pliable", "brittle", "sturdy", "fragile", "robust", "delicate", "durable", "flimsy", "solid", "hollow", "dense", "sparse", "compact", "loose", "tight", "baggy", "snug", "roomy", "dry", "wet", "moist", "arid", "damp", "parched", "soaked", "dehydrated", "saturated", "empty", "full", "vacant", "occupied", "bare", "crowded", "deserted", "packed", "sparse", "abundant", "scarce", "plentiful", "rich", "poor", "wealthy", "impoverished", "affluent", "destitute", "prosperous", "needy", "expensive", "cheap", "costly", "inexpensive", "valuable", "worthless", "precious", "common"],
  "adj-animate":["lively", "energetic", "sleepy", "alert", "drowsy", "active", "agile", "clumsy", "graceful", "awkward", "nimble", "quick", "slow", "fast", "speedy", "unhurried", "swift", "rapid", "deliberate", "cautious", "bold", "timid", "brave", "cowardly", "fearless", "anxious", "confident", "insecure", "assertive", "submissive", "dominant", "meek", "aggressive", "passive", "fierce", "gentle", "wild", "tame", "feral", "domesticated", "savage", "docile", "vicious", "harmless", "dangerous", "safe", "threatening", "friendly", "hostile", "affectionate", "aloof", "loving", "indifferent", "caring", "neglectful", "nurturing", "abusive", "protective", "negligent", "loyal", "treacherous", "faithful", "unfaithful", "devoted", "disloyal", "obedient", "disobedient", "compliant", "rebellious", "trainable", "unruly", "disciplined", "uncontrollable", "cooperative", "uncooperative", "sociable", "antisocial", "gregarious", "solitary", "outgoing", "shy", "extroverted", "introverted", "playful", "serious", "mischievous", "solemn", "frisky", "sedate", "boisterous", "quiet", "noisy", "silent", "vocal", "mute", "talkative", "reserved", "chatty", "taciturn", "communicative", "uncommunicative", "expressive", "inexpressive", "responsive", "unresponsive", "sensitive", "insensitive", "empathetic", "apathetic", "compassionate", "indifferent", "kind", "cruel", "gentle", "harsh", "benevolent", "malevolent", "altruistic", "selfish", "generous", "greedy", "sharing", "hoarding", "giving", "taking", "helpful", "unhelpful", "supportive", "unsupportive", "cooperative", "competitive", "peaceful", "aggressive", "calm", "agitated", "relaxed", "stressed", "composed", "flustered", "tranquil", "anxious", "serene", "nervous", "content", "restless", "satisfied", "dissatisfied", "happy", "sad", "joyful", "sorrowful", "cheerful", "gloomy", "excited", "elated", "dejected", "ecstatic", "miserable", "pleased", "displeased", "delighted", "upset", "angry", "peaceful", "furious", "serene", "enraged", "placid", "irritated", "patient", "annoyed", "tolerant", "frustrated", "accepting"]
};
compareWords("noun-animate");
